<?php
/** @var $block Template */

use Magento\Cms\Block\Block;
use Magento\Framework\View\Element\Template;

$blockLayout    = $this->getLayout()->createBlock(Block::class);
$topBrandsHTML  = $blockLayout->setBlockId("top_brands")->toHtml();

?>

<div class="container mb-32 px-8 lg:px-0">

    <?=$topBrandsHTML?>

</div>

<script>
    require([
        'jquery',
        'slick'
    ], function ($) {
        $(document).ready(function () {
            $(".top-brands-slider").slick({
                dots: false,
                infinite: true,
                speed: 300,
                slidesToShow: 5,
                slidesToScroll: 2,
                responsive: [
                    {
                        breakpoint: 1280,
                        settings: {
                            slidesToShow: 4,
                            slidesToScroll: 3
                        }
                    },
                    {
                        breakpoint: 760,
                        settings: {
                            slidesToShow: 3,
                            slidesToScroll: 2
                        }
                    },
                    {
                        breakpoint: 600,
                        settings: {
                            slidesToShow: 2,
                            slidesToScroll: 1
                        }
                    },
                    {
                        breakpoint: 376,
                        settings: {
                            slidesToShow: 2,
                            slidesToScroll: 1
                        }
                    }
                ]
            });
        });
    });
</script>
