<?php
/** @var $block Template */

use Magento\Cms\Block\Block;
use Magento\Framework\View\Element\Template;

$blockLayout = $this->getLayout()->createBlock(Block::class);
$teaserHTML  = $blockLayout->setBlockId("footer_main_information")->toHtml();

?>

<div class="container my-24 lg:mb-6 px-12 lg:px-8 ">
    <div class="border-primary border-t-2 pt-4 w-40 mb-4 py-4"></div>
    <div class="w-full mb-24">
        <?=$teaserHTML?>
    </div>
    <div class="relative h-full overflow-visible toggle-div">
        <a href="javascript:void(0);" class="inline-block w-full button-toggle-content">
            <p class="bg-gradient-to-t from-white via-white -mt-40 py-12">
                <svg class="w-9 h-9 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8l4 4m0 0l-4 4m4-4H3"></path>
                </svg>
            </p>
        </a>
    </div>
</div>
